### ISSUE TITLE
Null Safety?

### ISSUE THREAD

**Issue by chipweinberger** [tekartik/midi.dart#20]
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:tekartik_midi
 - package:tekartik_common_utils


For solutions, see https://dart.dev/go/unsound-null-safety
```

Thanks for this library! It looks well coded! =)

**Comment by chipweinberger** [comment]
`version: 0.3.4`

Ah, looks like I downloaded the wrong version somwhow.  

I just did this 

```
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
      ref: dart2
```

like the readme specifies.

**Comment by alextekartik** [comment]
As of today you should use the dart2_3 branch - [Note about versioning.](https://github.com/tekartik/common.dart/blob/main/doc/tekartik_versioning.md):

```yaml
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
      ref: dart2_3
```
